### ISSUE TITLE
KeyError: "EncoderDecoder: 'pvt_v2_b4 is not in the models registry'"

### ISSUE THREAD

**Issue by oszn** [whai362/PVTv2-Seg#1]
KeyError: "EncoderDecoder: 'pvt_v2_b4 is not in the models registry'"

**Comment by czczup** [comment]
> KeyError: "EncoderDecoder: 'pvt_v2_b4 is not in the models registry'"

When using test.py? I fixed this bug, just `import pvtv2`.
